// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CopyDotnetTestCommand
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSTestMenuString = "1e198c22-5980-4e7e-92f3-f73168d1fb63";
        public static Guid guidVSTestMenu = new Guid(guidVSTestMenuString);

        public const string guidExtensionPackageString = "2fdf8c53-bdfb-4e73-a913-55028db0bcc7";
        public static Guid guidExtensionPackage = new Guid(guidExtensionPackageString);

        public const string guidExtensionPackageCmdSetString = "1483248f-15ce-428f-becb-c73684dd498e";
        public static Guid guidExtensionPackageCmdSet = new Guid(guidExtensionPackageCmdSetString);

        public const string guidTestProjectUIContextString = "8101a265-27a0-48e7-b34b-a9ad6a37f282";
        public static Guid guidTestProjectUIContext = new Guid(guidTestProjectUIContextString);

        public const string guidCSharpEditorString = "a6c744a8-0e4a-4fc6-886a-064283054674";
        public static Guid guidCSharpEditor = new Guid(guidCSharpEditorString);

        public const string guidCSharpEditorWithEncodingString = "08467b34-b90f-4d91-bdca-eb8c8cf3033a";
        public static Guid guidCSharpEditorWithEncoding = new Guid(guidCSharpEditorWithEncodingString);

        public const string guidFSharpEditorString = "8a5aa6cf-46e3-4520-a70a-7393d15233e9";
        public static Guid guidFSharpEditor = new Guid(guidFSharpEditorString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int IDM_VS_MENU_TEST = 0x0001;
        public const int CopyCommandMenuGroupId = 0x1020;
        public const int CopyCommandId = 0x0100;
    }
}