// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CopyDotnetTestCommand
{
    internal sealed partial class Vsix
    {
        public const string Id = "CopyDotnetTestCommand.92c4e2aa-7c31-4a02-949b-29d58a1e1589";
        public const string Name = "CopyDotnetTestCommand";
        public const string Description = @"With this extension, you can easily copy the .NET Core CLI command to execute one or several unit tests to the clipboard.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Florian Gerlinghoff";
        public const string Tags = "";
    }
}
